name: SILShack Summer 2017

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  
future: true

timezone: America/New_York

# You betcha
gems:
  - jemoji

# Categories to exclude from the index
special-categories: 
  - "exercise"
  - "how-to"
  - "sidebar"
  - "reading"
  - "notes"
  
# Exclude Jekyll's built-in tests
exclude: [vendor]

# These can contain uppercase: they'll be lowercased in the URL
page-order:
  - syllabus
  - schedule
  - assignments
  - how-to
  - people

# Same note RE case above
python-extra-pages:
  - console
  
  
permalink: none
  
baseurl: /spring2016
url: /spring2016

python: true

course:
  title: Programming for Information Professionals
  number: INLS 560
  instructor: Prof. Elliott Hauser
  semester: Summer 2017

authors:
  elliott:
      name: Elliott Hauser
      prof: true
      gravatar: 0d0d432948d262195358f339768f1240
      website: http://www.elliotthauser.com
      github: eah13
      twitter: hauspoor
      about:  Elliott Hauser is a PhD Student in information science at UNC Chapel Hill.  He's hacking education as one of the cofounders of Trinket.io.  

  tommytester:
      name: Tommy the Tester
      prof: false
      gravatar:
      website: https://www.google.com/search?q=tommy+tester&rlz=1CAACAG_enUS613US613&oq=tommy+tester&aqs=chrome..69i57j0l5.2034j0j7&sourceid=chrome&es_sm=92&ie=UTF-8
      github: tommytester
      twitter: tommytester
      about: "Tommy is our tester account.  We'll use him to scope out how to use github"